[tox]
envlist =
    format
    lint
    py{36,37,38,39,310,311,312,313,314}
minversion = 4.0
ignore_basepython_conflict = True
skip_missing_interpreters = True

[testenv]
basepython = python3.14
deps =
    -rrequirements-tests.txt
commands =
    pytest {posargs:test_ttyscan.py --strict-markers --verbose --durations=50}

[testenv:format]
basepython = python3.13
deps =
    autopep8
commands =
    autopep8 --in-place --aggressive --aggressive ttyscan.py test_ttyscan.py

[testenv:lint]
basepython = python3.14
deps =
    flake8
commands =
    flake8 ttyscan.py test_ttyscan.py

[coverage:run]
source = ttyscan

[coverage:report]
precision = 1
exclude_lines =
    pragma: no cover

[pytest]
addopts =
    --cov=ttyscan
    --cov-append
    --cov-report=xml
    --cov-report=term-missing
faulthandler_timeout = 30

[flake8]
max-line-length = 100
exclude = .tox,build,dist,__pycache__
